### PR TITLE
WriteHat API

### PR DESCRIPTION
**Pull request by thejohnbrown**
Hi,

As briefly discussed [here](https://github.com/blacklanternsecurity/writehat/issues/51), I have started creating a REST API for WriteHat. It is still under development and is missing some functionality but I feel this is a solid foundation for the API to be built upon.

I've updated the README with some details about how it works but as a summary:

### Authentication

Authentication is handled via [tokens](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) which can be generated from the /admin dashboard. Tokens must be sent as a HTTP request header in the following format `Authorization: Token <token>`.

### Functionality

The API currently supports the following functionality:

#### Engagements

* List all engagements, reports and finding groups
* Get engagement, report and finding group details
* Create, update and delete engagements
* Create, update and delete reports
* Create, update and delete finding groups

#### Customers

* List all customers
* Get customer details
* Create, update and delete customer

#### Templates

* List all report and page templates

### CODE REVIEW

**Comment by thejohnbrown** [comment]
Sorry, I was meant to raise a PR to merge this into the github-dev branch instead of master as it's obviously unfinished functionality. Can you change that on your end? Or do you need me to re-raise the PR?

**Comment by kerrymilan** [comment]
Hey @thejohnbrown, thanks so much for the PR! Like @TheTechromancer said, a REST API has been on our list for a while. This looks like a great start and we really appreciate you taking the time to implement it. We'll pull these changes into the dev branch as soon as we've reviewed them.

**Comment by kerrymilan** [comment]
Are you open to using ViewSets instead of Views? I've checked in a proposed change for the Engagement and Customer models to our own writehat-api branch as an example (47e23df).

Reviewing these changes makes me realize how much work we need to do to refactor the model to make sure some of our earlier design decisions don't carry over into the API. As an example, I've implemented foreign keys between Engagement<>Customer and Engagement<>FindingGroup. I don't think that will cause any migration issues but I'll continue testing next week.

**Comment by thejohnbrown** [comment]
Yeah, ViewSets look much cleaner. My lack of Django experience is showing through here haha, ViewSets could have saved me a lot of time!

**Comment by kerrymilan** [comment]
No worries! That was a huge lesson learned for us too (as well as the use of DRF in general). ViewSets cut out a ton of redundant code. They do tend to fall short in more complex use cases, although you can push that limit to an extent by supplementing with custom `@action`s and using the `drf-nested-routers` extension. 

If you need to override the built-in functionality, you have to implement [these actions](https://www.django-rest-framework.org/api-guide/viewsets/#viewset-actions) instead of the usual `get`, `post`, etc. There are some cases, particularly when implementing a custom action, where you'll want to reimplement the `get_serializer` method to format the output differently based on `request.action`.

If you want to take a swing at implementing the rest of these classes as viewsets, I think it should be pretty straightforward. You may need to refactor some of the models' `UUIDField`s as `ForeignKey`s similar to [this](https://github.com/blacklanternsecurity/writehat/blob/writehat-api/writehat/lib/engagement.py#L21). Anything that deals with `Component`s is likely to be a heavier lift since those go through the Mongo backend; let us know when you get to that point and we'll figure out what needs to be reworked to accommodate the API.

**Pull request closed without merging**
